## 실행 전 jsonl 폴더 만들어주기
## 01_자본시장과금융투자업에관한법률
python make_keyword_graph.py --data_type 법 --original_file_path ../data/DCM/DCM_json/01/01_law_main.json --input_jsonl_path ../data/DCM/DCM_json/01/jsonl/01_law_main_definition_text_preprocessed_chunking.jsonl --triplet_jsonl_path ../data/DCM/DCM_json/01/jsonl/01_law_main_triplet_preprocessed_chunking_cot.jsonl --meta_path ../data/DCM/DCM_json/01/jsonl/01_law_main_definition_metadata_preprocessed_chunking_cot.csv --resume True
python make_keyword_graph.py --data_type 시행령 --original_file_path ../data/DCM/DCM_json/01/01_enforcement_main.json --input_jsonl_path ../data/DCM/DCM_json/01/jsonl/01_enforcement_main_definition_text_preprocessed_chunking.jsonl --triplet_jsonl_path ../data/DCM/DCM_json/01/jsonl/01_enforcement_main_triplet_preprocessed_chunking_cot.jsonl --meta_path ../data/DCM/DCM_json/01/jsonl/01_enforcement_main_definition_metadata_preprocessed_chunking_cot.csv --resume True
python make_keyword_graph.py --data_type 시행규칙 --original_file_path ../data/DCM/DCM_json/01/01_order_main.json --input_jsonl_path ../data/DCM/DCM_json/01/jsonl/01_order_main_definition_text_preprocessed_chunking.jsonl --triplet_jsonl_path ../data/DCM/DCM_json/01/jsonl/01_order_main_triplet_preprocessed_chunking_cot.jsonl --meta_path ../data/DCM/DCM_json/01/jsonl/01_order_main_definition_metadata_preprocessed_chunking_cot.csv --resume True

# ## 02_금융지주회사감독규정
# python make_keyword_graph.py --data_type 법 --original_file_path ../data/DCM/DCM_json/02/02_law_main.json --input_jsonl_path ../data/DCM/DCM_json/02/jsonl/02_law_main_definition_text_preprocessed_chunking.jsonl --triplet_jsonl_path ../data/DCM/DCM_json/02/jsonl/02_law_main_triplet_preprocessed_chunking_cot.jsonl --meta_path ../data/DCM/DCM_json/02/jsonl/02_law_main_definition_metadata_preprocessed_chunking_cot.csv --resume True
# python make_keyword_graph.py --data_type 시행령 --original_file_path ../data/DCM/DCM_json/02/02_enforcement_main.json --input_jsonl_path ../data/DCM/DCM_json/02/jsonl/02_enforcement_main_definition_text_preprocessed_chunking.jsonl --triplet_jsonl_path ../data/DCM/DCM_json/02/jsonl/02_enforcement_main_triplet_preprocessed_chunking_cot.jsonl --meta_path ../data/DCM/DCM_json/02/jsonl/02_enforcement_main_definition_metadata_preprocessed_chunking_cot.csv --resume True
# python make_keyword_graph.py --data_type 시행규칙 --original_file_path ../data/DCM/DCM_json/02/02_order_main.json --input_jsonl_path ../data/DCM/DCM_json/02/jsonl/02_order_main_definition_text_preprocessed_chunking.jsonl --triplet_jsonl_path ../data/DCM/DCM_json/02/jsonl/02_order_main_triplet_preprocessed_chunking_cot.jsonl --meta_path ../data/DCM/DCM_json/02/jsonl/02_order_main_definition_metadata_preprocessed_chunking_cot.csv --resume True

# ## 03_증권의발행및공시등에관한규정
# python make_keyword_graph.py --data_type 규정 --original_file_path ../data/DCM/DCM_json/03/03_regulation_main.json --input_jsonl_path ../data/DCM/DCM_json/03/jsonl/03_regulation_main_definition_text_preprocessed_chunking.jsonl --triplet_jsonl_path ../data/DCM/DCM_json/03/jsonl/03_regulation_main_triplet_preprocessed_chunking_cot.jsonl --meta_path ../data/DCM/DCM_json/03/jsonl/03_regulation_main_definition_metadata_preprocessed_chunking_cot.csv --resume True

# ## 04_kofia
# python make_keyword_graph.py --data_type 규정 --original_file_path ../data/DCM/DCM_json/04/04_regulation_main.json --input_jsonl_path ../data/DCM/DCM_json/04/jsonl/04_regulation_main_definition_text_preprocessed_chunking.jsonl --triplet_jsonl_path ../data/DCM/DCM_json/04/jsonl/04_regulation_main_triplet_preprocessed_chunking_cot.jsonl --meta_path ../data/DCM/DCM_json/03/jsonl/03_regulation_main_definition_metadata_preprocessed_chunking_cot.csv --resume True

# ## 08_은행법
# python make_keyword_graph.py --data_type 법 --original_file_path ../data/DCM/DCM_json/08/08_law_main.json --input_jsonl_path ../data/DCM/DCM_json/08/jsonl/08_law_main_definition_text_preprocessed_chunking.jsonl --triplet_jsonl_path ../data/DCM/DCM_json/08/jsonl/08_law_main_triplet_preprocessed_chunking_cot.jsonl --meta_path ../data/DCM/DCM_json/08/jsonl/08_law_main_definition_metadata_preprocessed_chunking_cot.csv --resume True
# python make_keyword_graph.py --data_type 시행령 --original_file_path ../data/DCM/DCM_json/08/08_enforcement_main.json --input_jsonl_path ../data/DCM/DCM_json/08/jsonl/08_enforcement_main_definition_text_preprocessed_chunking.jsonl --triplet_jsonl_path ../data/DCM/DCM_json/08/jsonl/08_enforcement_main_triplet_preprocessed_chunking_cot.jsonl --meta_path ../data/DCM/DCM_json/08/jsonl/08_enforcement_main_definition_metadata_preprocessed_chunking_cot.csv --resume True